create table blog_schema.blog_details (
        id NUMBER generated by default as identity,
        owner_id NUMBER,
        category VARCHAR2(200),
        content VARCHAR2(200),
        title VARCHAR2(200),
        primary key (id)
    );


create table owner_schema.owner_details (
        id NUMBER generated by default as identity,
        email VARCHAR2(200),
        name VARCHAR2(200),
        primary key (id)
    );