create table blog_schema.blog_details (
        id NUMBER generated by default as identity,
        owner_id NUMBER,
        category VARCHAR2(400),
        content VARCHAR2(400),
        title VARCHAR2(400),
        primary key (id)
    );


create table owner_schema.owner_details (
        id NUMBER generated by default as identity,
        email VARCHAR2(400),
        name VARCHAR2(400),
        primary key (id)
    );