create table blog_schema.blog_details (
        id integer generated by default as identity,
        owner_id integer,
        category varchar(255),
        content varchar(255),
        title varchar(255),
        primary key (id)
    );


create table owner_schema.owner_details (
        id integer generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );