create table blog_schema.blog_details (
        id INT generated by default as identity,
        owner_id INT,
        category VARCHAR(100),
        content VARCHAR(100),
        title VARCHAR(100),
        primary key (id)
    );


create table owner_schema.owner_details (
        id INT generated by default as identity,
        email VARCHAR(100),
        name VARCHAR(100),
        primary key (id)
    );