spring:
  datasource:
    url: jdbc:h2:mem:testDb;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:h2/schema.sql'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql, classpath*:mysql/ddl.sql
      data-locations: classpath*:h2/data*.sql